https://www.kaggle.com/competitions/spaceship-titanic

# Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter('ignore')
import seaborn as sns

In [2]:
from sklearn.naive_bayes import GaussianNB , BernoulliNB # 2 şey için
from sklearn.naive_bayes import MultinomialNB# 3 ve daha fazla için
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier,ExtraTreesClassifier,RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Importing DF

In [3]:
df1=pd.read_csv("train.csv")

In [4]:
df2=pd.read_csv("test.csv")

# EDA

In [5]:
df1.tail()

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True

In [6]:
df2.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [7]:
df1.shape

(8693, 14)

In [8]:
df2.shape

(4277, 13)

In [9]:
df=df1.append(df2)

In [10]:
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

  Transported  
0       False  
1        True  
2       False  
3       False  
4        True

In [11]:
df.shape

(12970, 14)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   12970 non-null  object 
 1   HomePlanet    12682 non-null  object 
 2   CryoSleep     12660 non-null  object 
 3   Cabin         12671 non-null  object 
 4   Destination   12696 non-null  object 
 5   Age           12700 non-null  float64
 6   VIP           12674 non-null  object 
 7   RoomService   12707 non-null  float64
 8   FoodCourt     12681 non-null  float64
 9   ShoppingMall  12664 non-null  float64
 10  Spa           12686 non-null  float64
 11  VRDeck        12702 non-null  float64
 12  Name          12676 non-null  object 
 13  Transported   8693 non-null   object 
dtypes: float64(6), object(8)
memory usage: 1.5+ MB


In [13]:
df.isnull().sum()

PassengerId        0
HomePlanet       288
CryoSleep        310
Cabin            299
Destination      274
Age              270
VIP              296
RoomService      263
FoodCourt        289
ShoppingMall     306
Spa              284
VRDeck           268
Name             294
Transported     4277
dtype: int64

In [14]:
df.corr()

Age  RoomService  FoodCourt  ShoppingMall       Spa  \
Age           1.000000     0.067300   0.124447      0.034959  0.118992   
RoomService   0.067300     1.000000  -0.020146      0.057402  0.008936   
FoodCourt     0.124447    -0.020146   1.000000     -0.001589  0.228990   
ShoppingMall  0.034959     0.057402  -0.001589      1.000000  0.010504   
Spa           0.118992     0.008936   0.228990      0.010504  1.000000   
VRDeck        0.101441    -0.023847   0.244279      0.004485  0.149874   

                VRDeck  
Age           0.101441  
RoomService  -0.023847  
FoodCourt     0.244279  
ShoppingMall  0.004485  
Spa           0.149874  
VRDeck        1.000000

In [15]:
df.describe()

Age   RoomService     FoodCourt  ShoppingMall           Spa  \
count  12700.000000  12707.000000  12681.000000  12664.000000  12686.000000   
mean      28.771969    222.897852    451.961675    174.906033    308.476904   
std       14.387261    647.596664   1584.370747    590.558690   1130.279641   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%       19.000000      0.000000      0.000000      0.000000      0.000000   
50%       27.000000      0.000000      0.000000      0.000000      0.000000   
75%       38.000000     49.000000     77.000000     29.000000     57.000000   
max       79.000000  14327.000000  29813.000000  23492.000000  22408.000000   

             VRDeck  
count  12702.000000  
mean     306.789482  
std     1180.097223  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%       42.000000  
max    24133.000000

In [16]:
df.shape

(12970, 14)

# Deep understanding

In [17]:
df.isnull().sum()

PassengerId        0
HomePlanet       288
CryoSleep        310
Cabin            299
Destination      274
Age              270
VIP              296
RoomService      263
FoodCourt        289
ShoppingMall     306
Spa              284
VRDeck           268
Name             294
Transported     4277
dtype: int64

In [18]:
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

  Transported  
0       False  
1        True  
2       False  
3       False  
4        True

In [19]:
df["PassengerId"].nunique()

12970

In [20]:
 df["HomePlanet"].value_counts() #Dummy

Earth     6865
Europa    3133
Mars      2684
Name: HomePlanet, dtype: int64

In [21]:
df["HomePlanet"].fillna("Earth",inplace=True)

In [22]:
df["CryoSleep"].value_counts() # Dummy

False    8079
True     4581
Name: CryoSleep, dtype: int64

In [23]:
df["CryoSleep"].fillna("False",inplace=True)

In [24]:
df["Cabin"].nunique() # DEL

9825

In [25]:
df["Destination"].value_counts() #dummy

TRAPPIST-1e      8871
55 Cancri e      2641
PSO J318.5-22    1184
Name: Destination, dtype: int64

In [26]:
df["Destination"].fillna("TRAPPIST-1e",inplace=True)

In [27]:
df["Age"].median()

27.0

In [28]:
df["Age"].fillna(27.0,inplace=True)

In [29]:
df["VIP"].value_counts()

False    12401
True       273
Name: VIP, dtype: int64

In [30]:
df["VIP"].fillna("False",inplace=True) # Dummy

In [31]:
df["RoomService"].median()

0.0

In [32]:
df["RoomService"].fillna(0.0,inplace=True)

In [33]:
df["FoodCourt"].median()

0.0

In [34]:
df["FoodCourt"].fillna(0.0,inplace=True)

In [35]:
df["ShoppingMall"].median()

0.0

In [36]:
df["ShoppingMall"].fillna(0.0,inplace=True)

In [37]:
df["Spa"].median()

0.0

In [38]:
df["Spa"].fillna(0.0,inplace=True)

In [39]:
df["VRDeck"].median()

0.0

In [40]:
df["VRDeck"].fillna(0.0,inplace=True)

In [41]:
df["Transported"][1][1]

1    True
1     NaN
Name: Transported, dtype: object

In [42]:
for i in range(df.shape[0]):
    if df["Transported"].iloc[i]==False:
        df["Transported"].iloc[i]=0
    elif df["Transported"].iloc[i]==True:
        df["Transported"].iloc[i]=1
    else:
        a=2

In [43]:
df=df.drop(["Cabin","Name"],axis=1)

In [44]:
df.isnull().sum()

PassengerId        0
HomePlanet         0
CryoSleep          0
Destination        0
Age                0
VIP                0
RoomService        0
FoodCourt          0
ShoppingMall       0
Spa                0
VRDeck             0
Transported     4277
dtype: int64

In [45]:
df3=df.iloc[:8693,]
df4=df.iloc[8693:,]

In [46]:
df3["Transported"]=df3["Transported"].astype(int)

In [47]:
df3.corr()

Age  RoomService  FoodCourt  ShoppingMall       Spa  \
Age           1.000000     0.068629   0.127390      0.033148  0.120946   
RoomService   0.068629     1.000000  -0.015126      0.052337  0.009244   
FoodCourt     0.127390    -0.015126   1.000000     -0.013717  0.221468   
ShoppingMall  0.033148     0.052337  -0.013717      1.000000  0.014542   
Spa           0.120946     0.009244   0.221468      0.014542  1.000000   
VRDeck        0.099590    -0.018624   0.224572     -0.007849  0.147658   
Transported  -0.074233    -0.241124   0.045583      0.009391 -0.218545   

                VRDeck  Transported  
Age           0.099590    -0.074233  
RoomService  -0.018624    -0.241124  
FoodCourt     0.224572     0.045583  
ShoppingMall -0.007849     0.009391  
Spa           0.147658    -0.218545  
VRDeck        1.000000    -0.204874  
Transported  -0.204874     1.000000

In [48]:
abs(df3.corr()["Transported"]).sort_values(ascending=False)

Transported     1.000000
RoomService     0.241124
Spa             0.218545
VRDeck          0.204874
Age             0.074233
FoodCourt       0.045583
ShoppingMall    0.009391
Name: Transported, dtype: float64

In [49]:
df["RoomService"]=df["RoomService"]*2
df["Spa"]=df["Spa"]*2

- spliting test and train

In [50]:
x=df.iloc[:8693,]
y=df.iloc[8693:,]

In [51]:
x.head()

PassengerId HomePlanet CryoSleep  Destination   Age    VIP  RoomService  \
0     0001_01     Europa     False  TRAPPIST-1e  39.0  False          0.0   
1     0002_01      Earth     False  TRAPPIST-1e  24.0  False        218.0   
2     0003_01     Europa     False  TRAPPIST-1e  58.0   True         86.0   
3     0003_02     Europa     False  TRAPPIST-1e  33.0  False          0.0   
4     0004_01      Earth     False  TRAPPIST-1e  16.0  False        606.0   

   FoodCourt  ShoppingMall      Spa  VRDeck Transported  
0        0.0           0.0      0.0     0.0           0  
1        9.0          25.0   1098.0    44.0           1  
2     3576.0           0.0  13430.0    49.0           0  
3     1283.0         371.0   6658.0   193.0           0  
4       70.0         151.0   1130.0     2.0           1

In [52]:
pasidy=y["PassengerId"]
pasidx=x["PassengerId"]

In [53]:
z=x[["Transported"]]

In [54]:
x.drop(["Transported","PassengerId"],axis=1,inplace=True)

In [55]:
y.drop(["Transported","PassengerId"],axis=1,inplace=True)

In [56]:
x.shape

(8693, 10)

In [57]:
y.shape

(4277, 10)

In [58]:
z.shape

(8693, 1)

In [59]:
x.head()

HomePlanet CryoSleep  Destination   Age    VIP  RoomService  FoodCourt  \
0     Europa     False  TRAPPIST-1e  39.0  False          0.0        0.0   
1      Earth     False  TRAPPIST-1e  24.0  False        218.0        9.0   
2     Europa     False  TRAPPIST-1e  58.0   True         86.0     3576.0   
3     Europa     False  TRAPPIST-1e  33.0  False          0.0     1283.0   
4      Earth     False  TRAPPIST-1e  16.0  False        606.0       70.0   

   ShoppingMall      Spa  VRDeck  
0           0.0      0.0     0.0  
1          25.0   1098.0    44.0  
2           0.0  13430.0    49.0  
3         371.0   6658.0   193.0  
4         151.0   1130.0     2.0

In [60]:
x=pd.get_dummies(x,drop_first=True)
y=pd.get_dummies(y,drop_first=True)

In [61]:
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
col=x.columns
x_scaled = scale.fit_transform(x)
x= pd.DataFrame(x_scaled,columns=col)
x.head()

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0  0.493671     0.000000   0.000000      0.000000  0.000000  0.000000   
1  0.303797     0.007608   0.000302      0.001064  0.024500  0.001823   
2  0.734177     0.003001   0.119948      0.000000  0.299670  0.002030   
3  0.417722     0.000000   0.043035      0.015793  0.148563  0.007997   
4  0.202532     0.021149   0.002348      0.006428  0.025214  0.000083   

   HomePlanet_Europa  HomePlanet_Mars  CryoSleep_True  CryoSleep_False  \
0                1.0              0.0             0.0              0.0   
1                0.0              0.0             0.0              0.0   
2                1.0              0.0             0.0              0.0   
3                1.0              0.0             0.0              0.0   
4                0.0              0.0             0.0              0.0   

   Destination_PSO J318.5-22  Destination_TRAPPIST-1e  VIP_True  VIP_False  
0                        0.0                      1.0       0.0        0.0  
1                        0.0                      1.0       0.0        0.0  
2                        0.0                      1.0       1.0        0.0  
3                        0.0                      1.0       0.0        0.0  
4                        0.0                      1.0       0.0        0.0

In [62]:
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
col=y.columns
y_scaled = scale.fit_transform(y)
y= pd.DataFrame(y_scaled,columns=col)
y.head()

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0  0.341772     0.000000   0.000000       0.00000  0.000000  0.000000   
1  0.240506     0.000000   0.000356       0.00000  0.142260  0.000000   
2  0.392405     0.000000   0.000000       0.00000  0.000000  0.000000   
3  0.481013     0.000000   0.263206       0.00000  0.009121  0.026266   
4  0.253165     0.000865   0.000000       0.07658  0.000000  0.000000   

   HomePlanet_Europa  HomePlanet_Mars  CryoSleep_True  CryoSleep_False  \
0                0.0              0.0             1.0              0.0   
1                0.0              0.0             0.0              0.0   
2                1.0              0.0             1.0              0.0   
3                1.0              0.0             0.0              0.0   
4                0.0              0.0             0.0              0.0   

   Destination_PSO J318.5-22  Destination_TRAPPIST-1e  VIP_True  VIP_False  
0                        0.0                      1.0       0.0        0.0  
1                        0.0                      1.0       0.0        0.0  
2                        0.0                      0.0       0.0        0.0  
3                        0.0                      1.0       0.0        0.0  
4                        0.0                      1.0       0.0        0.0

In [63]:
g=GaussianNB()
b=BernoulliNB()
k=KNeighborsClassifier(n_neighbors=5)
d=DecisionTreeClassifier(min_samples_leaf=5,max_features=0.5)
gbc=GradientBoostingClassifier(n_estimators=1500)
etc=ExtraTreesClassifier()
svc=SVC()
rfc=RandomForestClassifier(n_jobs=-1, n_estimators=400,
                                  max_features=0.5, min_samples_leaf=5, oob_score=True)
log=LogisticRegression()

In [64]:
x.head()

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0  0.493671     0.000000   0.000000      0.000000  0.000000  0.000000   
1  0.303797     0.007608   0.000302      0.001064  0.024500  0.001823   
2  0.734177     0.003001   0.119948      0.000000  0.299670  0.002030   
3  0.417722     0.000000   0.043035      0.015793  0.148563  0.007997   
4  0.202532     0.021149   0.002348      0.006428  0.025214  0.000083   

   HomePlanet_Europa  HomePlanet_Mars  CryoSleep_True  CryoSleep_False  \
0                1.0              0.0             0.0              0.0   
1                0.0              0.0             0.0              0.0   
2                1.0              0.0             0.0              0.0   
3                1.0              0.0             0.0              0.0   
4                0.0              0.0             0.0              0.0   

   Destination_PSO J318.5-22  Destination_TRAPPIST-1e  VIP_True  VIP_False  
0                        0.0                      1.0       0.0        0.0  
1                        0.0                      1.0       0.0        0.0  
2                        0.0                      1.0       1.0        0.0  
3                        0.0                      1.0       0.0        0.0  
4                        0.0                      1.0       0.0        0.0

In [65]:
z.head()

Transported
0           0
1           1
2           0
3           0
4           1

In [66]:
y.head()

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0  0.341772     0.000000   0.000000       0.00000  0.000000  0.000000   
1  0.240506     0.000000   0.000356       0.00000  0.142260  0.000000   
2  0.392405     0.000000   0.000000       0.00000  0.000000  0.000000   
3  0.481013     0.000000   0.263206       0.00000  0.009121  0.026266   
4  0.253165     0.000865   0.000000       0.07658  0.000000  0.000000   

   HomePlanet_Europa  HomePlanet_Mars  CryoSleep_True  CryoSleep_False  \
0                0.0              0.0             1.0              0.0   
1                0.0              0.0             0.0              0.0   
2                1.0              0.0             1.0              0.0   
3                1.0              0.0             0.0              0.0   
4                0.0              0.0             0.0              0.0   

   Destination_PSO J318.5-22  Destination_TRAPPIST-1e  VIP_True  VIP_False  
0                        0.0                      1.0       0.0        0.0  
1                        0.0                      1.0       0.0        0.0  
2                        0.0                      0.0       0.0        0.0  
3                        0.0                      1.0       0.0        0.0  
4                        0.0                      1.0       0.0        0.0

In [67]:
z.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8693 entries, 0 to 8692
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Transported  8693 non-null   object
dtypes: object(1)
memory usage: 135.8+ KB


In [68]:
z=z.astype(int)

In [69]:
z.head(50)

Transported
0             0
1             1
2             0
3             0
4             1
5             1
6             1
7             1
8             1
9             1
10            1
11            1
12            1
13            0
14            1
15            0
16            0
17            0
18            1
19            1
20            0
21            0
22            0
23            0
24            1
25            0
26            0
27            0
28            1
29            0
30            0
31            0
32            0
33            1
34            1
35            1
36            1
37            0
38            0
39            0
40            0
41            1
42            0
43            0
44            1
45            1
46            0
47            1
48            0
49            0

## Lets Predict!!!!!!!!

In [86]:
y_pred=g.fit(x,z).predict(y)
dfg=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfg["Transported"]= df5
dfg["PassengerId"]=pasidy
for i in range(dfg.shape[0]):
    if dfg["Transported"].iloc[i]==0:
        dfg["Transported"].iloc[i]=False
    elif dfg["Transported"].iloc[i]==1:
        dfg["Transported"].iloc[i]=True
    else:
        a=2
dfg.to_csv("final_datag.csv",index=False)

In [87]:
dfg["Transported"].unique()

array([True, False], dtype=object)

In [88]:
y_pred=b.fit(x,z).predict(y)
dfb=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfb["Transported"]= df5
dfb["PassengerId"]=pasidy
for i in range(dfb.shape[0]):
    if dfb["Transported"].iloc[i]==0:
        dfb["Transported"].iloc[i]=False
    elif dfb["Transported"].iloc[i]==1:
        dfb["Transported"].iloc[i]=True
    else:
        a=2
dfb.to_csv("final_datab.csv",index=False)

In [89]:
dfb["Transported"].unique()

array([True, False], dtype=object)

In [90]:
y_pred=k.fit(x,z).predict(y)
dfk=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfk["Transported"]= df5
dfk["PassengerId"]=pasidy
for i in range(dfg.shape[0]):
    if dfk["Transported"].iloc[i]==0:
        dfk["Transported"].iloc[i]=False
    elif dfk["Transported"].iloc[i]==1:
        dfk["Transported"].iloc[i]=True
    else:
        a=2
dfk.to_csv("final_dataknn.csv",index=False)

In [92]:
y_pred=d.fit(x,z).predict(y)
dfd=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfd["Transported"]= df5
dfd["PassengerId"]=pasidy
dfd.to_csv("final_datadtc.csv",index=False)

In [93]:
y_pred=gbc.fit(x,z).predict(y)
dfgbc=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfgbc["Transported"]= df5
dfgbc["PassengerId"]=pasidy
for i in range(dfgbc.shape[0]):
    if dfgbc["Transported"].iloc[i]==0:
        dfgbc["Transported"].iloc[i]=False
    elif dfgbc["Transported"].iloc[i]==1:
        dfgbc["Transported"].iloc[i]=True
    else:
        a=2
dfgbc.to_csv("final_datagbc.csv",index=False)

In [94]:
y_pred=svc.fit(x,z).predict(y)
dfsvc=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfsvc["Transported"]= df5
dfsvc["PassengerId"]=pasidy
for i in range(dfsvc.shape[0]):
    if dfsvc["Transported"].iloc[i]==0:
        dfsvc["Transported"].iloc[i]=False
    elif dfsvc["Transported"].iloc[i]==1:
        dfsvc["Transported"].iloc[i]=True
    else:
        a=2
dfsvc.to_csv("final_datasvc.csv",index=False)

In [95]:
dfsvc["Transported"].unique()

array([True, False], dtype=object)

In [96]:
dfsvc.head(50)

PassengerId Transported
0      0013_01        True
1      0018_01       False
2      0019_01        True
3      0021_01        True
4      0023_01       False
5      0027_01       False
6      0029_01        True
7      0032_01        True
8      0032_02        True
9      0033_01       False
10     0037_01       False
11     0040_01       False
12     0040_02        True
13     0042_01        True
14     0046_01       False
15     0046_02       False
16     0046_03       False
17     0047_01        True
18     0047_02        True
19     0047_03       False
20     0048_01       False
21     0049_01       False
22     0054_01        True
23     0054_02        True
24     0054_03        True
25     0055_01       False
26     0057_01        True
27     0059_01        True
28     0060_01       False
29     0063_01        True
30     0065_01        True
31     0075_01       False
32     0079_01        True
33     0080_01       False
34     0083_01       False
35     0087_01       False
36     0089_01        True
37     0093_01       False
38     0094_01        True
39     0094_02       False
40     0095_01       False
41     0096_01       False
42     0100_01       False
43     0100_02       False
44     0104_01       False
45     0106_01        True
46     0109_01       False
47     0117_01       False
48     0118_01       False
49     0121_01       False

In [98]:
y_pred=etc.fit(x,z).predict(y)
dfetc=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfetc["Transported"]= df5
dfetc["PassengerId"]=pasidy
for i in range(dfetc.shape[0]):
    if dfetc["Transported"].iloc[i]==0:
        dfetc["Transported"].iloc[i]=False
    elif dfetc["Transported"].iloc[i]==1:
        dfetc["Transported"].iloc[i]=True
    else:
        a=2
dfetc.to_csv("final_dataetc.csv",index=False)

In [99]:
dfetc["Transported"].unique()

array([True, False], dtype=object)

In [100]:
y_pred=rfc.fit(x,z).predict(y)
dfrfc=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dfrfc["Transported"]= df5
dfrfc["PassengerId"]=pasidy
for i in range(dfrfc.shape[0]):
    if dfrfc["Transported"].iloc[i]==0:
        dfrfc["Transported"].iloc[i]=False
    elif dfrfc["Transported"].iloc[i]==1:
        dfrfc["Transported"].iloc[i]=True
    else:
        a=2
dfrfc.to_csv("final_datarfc.csv",index=False)

In [101]:
dfrfc["Transported"].unique()

array([True, False], dtype=object)

In [102]:
y_pred=log.fit(x,z).predict(y)
dflog=pd.DataFrame(columns=["PassengerId","Transported"])
df5=pd.DataFrame(y_pred).astype(int)
dflog["Transported"]= df5
dflog["PassengerId"]=pasidy
for i in range(dfg.shape[0]):
    if dflog["Transported"].iloc[i]==0:
        dflog["Transported"].iloc[i]=False
    elif dflog["Transported"].iloc[i]==1:
        dflog["Transported"].iloc[i]=True
    else:
        a=2
dflog.to_csv("final_datalog.csv",index=False)

In [103]:
dflog["Transported"].unique()

array([True, False], dtype=object)